### ISSUE TITLE
API Application Form POST Isssue

### ISSUE THREAD

**Issue by biolinkid** [igorocampos/PDFFormFiller#1]
Unrecognized response type; displaying content as text.  When attempting to test the form population and download it returns the error unrecognized response, and the downloaded file is plain text unreadable.  Is there something I'm doing wrong?  I am using Docker to test as stated in the readme.  Without making any changes to the data being submitted in the POST command it still returns the same unrecognized type error.

**Comment by igorocampos** [comment]
It has been over 3 years since I touched this, let me set it up locally and check what can be going wrong, hang tight.

**Comment by biolinkid** [comment]
Thanks any help is greatly appreciated!




It has been over 3 years since I touched this, let me set it up locally and check what can be going wrong, hang tight.

**Comment by igorocampos** [comment]
Hi @biolinkid I was able to reproduce the error you mentioned. But it seems to be related to Swagger, please check https://github.com/swagger-api/swagger-ui/issues/5500 

However, if you actually consume the api using for instance Postman, you will be able to retrieve the PDF, look at the screenshot below

![image](https://user-images.githubusercontent.com/10572656/204092235-3474216e-c1bb-4753-a577-c84b0909d149.png)


I'll try doing some tweaks to see if I can get Swagger working, but meanwhile you can use the api with no issues :)

**Comment by igorocampos** [comment]
So according to the before mentioned GitHub issue [discussion](https://github.com/swagger-api/swagger-ui/issues/5500#issuecomment-550236506) a workaround is to set the response header with `Content-Type` as pdf file (this was already in place) and `Content-Disposition` as attachment.

According to this Stackoverflow [answer](https://stackoverflow.com/a/51216687) the content disposition header could be easily set by giving the download file a name, just adding a 3rd parameter to [line 70](https://github.com/igorocampos/PDFFormFiller/blob/e466fdc108f80975f676cbc7e1576c3094f06fd5/PDFFormFiller/Controllers/ApplicationFormController.cs#L70) of ApplicationFormController class, like this
```cs
return File(stream, "application/pdf", "ESDC-EMP5624.pdf");
``` 
If you are using .NET 6 the SO answer also has an update on how to do it properly.

All good now with the workaround, I'll soon update the repo with the 1 line change.

![image](https://user-images.githubusercontent.com/10572656/204094612-e33681ac-2ec2-4ad3-80ef-ffc44c011a12.png)
